// Demo dataset + merge with any custom vendors saved from subscription page
window.QS_DATA = (() => {
  const demo = [
    { id: 1, name: 'SparkFix Electricians', category: 'Electrician', rating: 4.7, distance_km: 0.8, tags: ['wiring','AC','fan'], description: 'Certified electricians for wiring, appliance installs, and quick fixes.', image: 'https://images.unsplash.com/photo-1581092336792-3e1c6c40f6d7?q=80&w=1200&auto=format&fit=crop' },
    { id: 2, name: 'PipePro Plumbers', category: 'Plumber', rating: 4.6, distance_km: 1.5, tags: ['leak','bath','kitchen'], description: 'Leak repairs, bathroom fitting, and emergency plumbing.', image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1200&auto=format&fit=crop' },
    { id: 3, name: 'RoadRescue Mechanics', category: 'Mechanic', rating: 4.5, distance_km: 2.1, tags: ['tyre','battery','service'], description: '24/7 roadside assistance and on-spot repair.', image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1200&auto=format&fit=crop' },
    { id: 4, name: 'FreshMart Grocery', category: 'Grocery', rating: 4.2, distance_km: 0.7, tags: ['fruits','veg','snacks'], description: 'Daily essentials and fresh produce delivered fast.', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1200&auto=format&fit=crop' },
    { id: 5, name: 'MediQuick Pharmacy', category: 'Pharmacy', rating: 4.4, distance_km: 1.2, tags: ['meds','health','wellness'], description: 'Prescription meds and wellness products at your doorstep.', image: 'https://images.unsplash.com/photo-1587854692152-1cfc1e7dc3cf?q=80&w=1200&auto=format&fit=crop' },
    { id: 6, name: 'BakeHouse', category: 'Bakery', rating: 4.3, distance_km: 1.0, tags: ['bread','cakes','pastry'], description: 'Fresh breads, cakes and pastries made daily.', image: 'https://images.unsplash.com/photo-1514516870926-2059896c24e9?q=80&w=1200&auto=format&fit=crop' },
    { id: 7, name: 'Wire&Care Electric', category: 'Electrician', rating: 4.1, distance_km: 2.9, tags: ['socket','inverter'], description: 'Affordable electrical maintenance and upgrades.', image: 'https://images.unsplash.com/photo-1572197498886-1e0fba9d8f87?q=80&w=1200&auto=format&fit=crop' },
    { id: 8, name: 'City Pipe Masters', category: 'Plumber', rating: 4.8, distance_km: 0.6, tags: ['heater','clog','sewage'], description: 'Expert plumbing with fair pricing and quick arrival.', image: 'https://images.unsplash.com/photo-1602749369442-9b64b7c7a7be?q=80&w=1200&auto=format&fit=crop' },
    { id: 9, name: 'CleanSweep Home', category: 'Cleaning', rating: 4.6, distance_km: 1.3, tags: ['deep clean','maid','organizing'], description: 'Professional home cleaning and organization services.', image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1200&auto=format&fit=crop' },
    { id: 10, name: 'TechGurus Repair', category: 'Electronics', rating: 4.9, distance_km: 2.4, tags: ['phone','laptop','TV'], description: 'Expert repair for all your electronic devices and gadgets.', image: 'https://images.unsplash.com/photo-1563207153-f403bf289096?q=80&w=1200&auto=format&fit=crop' },
    { id: 11, name: 'GreenThumb Gardeners', category: 'Gardening', rating: 4.4, distance_km: 3.2, tags: ['lawn','plants','landscaping'], description: 'Professional gardening and landscape maintenance services.', image: 'https://images.unsplash.com/photo-1589923188937-cb64779f4abe?q=80&w=1200&auto=format&fit=crop' },
    { id: 12, name: 'Pampered Pets Care', category: 'Pet Care', rating: 4.8, distance_km: 0.9, tags: ['grooming','walking','vet'], description: 'Complete pet care including grooming and veterinary services.', image: 'https://images.unsplash.com/photo-1561758033-48d52648ae8b?q=80&w=1200&auto=format&fit=crop' },
    { id: 13, name: 'FreshCut Salon', category: 'Salon', rating: 4.7, distance_km: 1.1, tags: ['haircut','spa','beauty'], description: 'Premium salon services for hair, skin, and beauty treatments.', image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=1200&auto=format&fit=crop' },
    { id: 14, name: 'FitLife Trainers', category: 'Fitness', rating: 4.5, distance_km: 0.5, tags: ['personal training','yoga','nutrition'], description: 'Certified personal trainers and fitness programs at your home.', image: 'https://lh3.googleusercontent.com/p/AF1QipOQaqTxs59xj6UBlhyS9KO05BKdIT66RO9SdQ4=s1360-w1360-h1020-rw' },
    { id: 15, name: 'SecureHome Locksmiths', category: 'Locksmith', rating: 4.9, distance_km: 2.7, tags: ['lock repair','key duplicate','security'], description: '24/7 emergency locksmith and home security services.', image: 'https://images.unsplash.com/photo-1601056639636-eca6a3f5e13c?q=80&w=1200&auto=format&fit=crop' },
    { id: 16, name: 'CarpetClean Pros', category: 'Cleaning', rating: 4.3, distance_km: 1.8, tags: ['carpet','upholstery','deep clean'], description: 'Professional carpet and upholstery cleaning services.', image: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?q=80&w=1200&auto=format&fit=crop' },
    { id: 17, name: 'ApplianceFix Experts', category: 'Appliance Repair', rating: 4.6, distance_km: 2.2, tags: ['refrigerator','washing machine','AC'], description: 'Expert repair for all home appliances with warranty.', image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=1200&auto=format&fit=crop' },
    { id: 18, name: 'MoveIt Packers', category: 'Moving', rating: 4.2, distance_km: 4.5, tags: ['packing','moving','relocation'], description: 'Stress-free packing and moving services for homes and offices.', image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1200&auto=format&fit=crop' }
  ];
  const custom = JSON.parse(localStorage.getItem('qs_vendors_custom') || '[]');
  return { vendors: [...custom, ...demo] };
})();
